### PR TITLE
Use `aarch64` suffix for ARM64 arch

### PR DESCRIPTION
**Pull request by reznikmm**
Refs https://github.com/alire-project/alire/issues/1666

### CODE REVIEW

**Comment by reznikmm** [comment]
@mosteo What can I do with this? CI fails just because there is no alr 2.0.1 for Mac OS X ARM64.

**Comment by mosteo** [comment]
This should start working the moment we have a stable release for aarch64, right? (after patching the downloads here). So it will only fail for people trying to install a non-existent aarch64 compiler. If this is so, we could simply merge as-is.

But what about the macos nightly test, that one should work, right?

**Comment by reznikmm** [comment]
Right. We *have* the compiler. Only gprbuild is missing currently.

Вт, 23 лип. 2024, 15:09 користувач Alejandro R Mosteo <
***@***.***> пише:

**Comment by mosteo** [comment]
Let's see IIUC: This was working until now because we always downloaded x86_64 on macOS, and this runs in some compatibility layer even on the new arm64 runners.

With this PR, when setup-alire is used from an aarch system, it will attemp to use an aarch64 installation, that don't yet exist.

Is that correct?

Assuming so: I see no urgency to merge this one before the proper tooling is available for arm64; even giving this PR the next major version can only confuse those that think that they can update to v4 without expecting trouble.

**Comment by reznikmm** [comment]
it depends on what you mean by ‘working’. If downloading x86_64 Alire which is not able to put aarch64 compiler is working, then you are right. But in my opinion it is not what users expect.

To summarize AArch64 support: 

|tool|exist|release|
|---|-----|-------|
|gnat_native|Yes|14.1.3|
|gprbuild|Yes|[PR 24.0](https://github.com/alire-project/alire-index/pull/1119)|
|alr|Yes|nightly|

So, merging this PR let me use it like this:
```yaml
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v4
        with:
          version: "nightly"
          toolchain: gnat_native^14 #gprbuild^24 # no gprbuild for ARM64
```
Then install gprbuild^24 from a custom index (until PR 1119 is merged). I need it in new GitHub Actions scripts for ada_language_server.

**Comment by mosteo** [comment]
I meant working in the sense that the action doesn't fail and the user ends with a usable toolchain, although I recognize it may be not the expected one.

My confusion wrt https://github.com/alire-project/alire-index/pull/1119 was that I thought you were providing that at AdaCore's initiative, but I must understand now that you're doing that on your own? I was waiting for approval from @Fabien-Chouteau on that one.

**Comment by reznikmm** [comment]
Sorry for confusion about `gprbuild`. Now we have both `gprbuild` and `gnat_native` in the community index. 

PS What can I do to help releasing alr 2.1.0 for Mac OS X ARM64?

**Comment by mosteo** [comment]
> PS What can I do to help releasing alr 2.1.0 for Mac OS X ARM64?

One thing we will need is a workflow in the alire repo that builds the arm64 version. We are now testing on macos-12, so we would need also to use macos-latest. The workflow is `ci-macos.yml`.

**Comment by mosteo** [comment]
Superseded by #82. Thanks for leading the way, Maxim.

**Pull request closed without merging**
